### ISSUE TITLE
Cannot enable in SSH

### ISSUE THREAD

**Issue by Cossey** [mattiarossi/prometheus-node-exporter-lua-technicolor#1]
I copied the files to the router via SSH and `0755`d the bin, config and initd files but then have issues when executing:
```
root@router:~# /etc/init.d/prometheus-node-exporter-lua enable
'bin/sh: can't open '/etc/rc.common
```

Version Info: `MediaAccess TG789MYRvac v2 HP GUI Version 9.6.90-d57fe377`

I **have not** installed any additional items like `LuCI GUI`. 

Interestingly, I can issue the command `lua prometheus-node-exporter-lua` which spits out the metrics to the shell.

**Comment by mattiarossi** [comment]
If you are not using Ansuel modded GUI you may be missing some directories, can you create /etc/rc.common? That may get you going. If as I fear the init script calls functions your firmware does not provide, can you post an existing init script that we can borrow code from?

**Comment by Cossey** [comment]
Thanks for following up - I do have Ansuel and am on the latest dev branch. 
`/etc/rc.common` already exists [rc.common.txt](https://github.com/mattiarossi/prometheus-node-exporter-lua-technicolor/files/7696717/rc.common.txt)

[dropbear.txt](https://github.com/mattiarossi/prometheus-node-exporter-lua-technicolor/files/7696718/dropbear.txt)
[telnet.txt](https://github.com/mattiarossi/prometheus-node-exporter-lua-technicolor/files/7696719/telnet.txt)

I did a reboot of the modem and the `prometheus-node-exporter-lua` shows up in the GUI under `Management > Init Management`.

Okay, looking at it now:
```
root@router:/etc/init.d# prometheus-node-exporter-lua enable
-ash: root@router:/etc/init.d#: not found
root@router:/etc/init.d# prometheus-node-exporter-lua start
-ash: prometheus-node-exporter-lua: not found
```

When I try the file directly:
```
root@router:/usr/bin# prometheus-node-exporter-lua
-ash: prometheus-node-exporter-lua: not found
```
The file does exist in the folder and is `0755`d.

*Note: `.txt` extensions have been added to files so I could upload them here*

**Comment by Cossey** [comment]
Okay, I figured out the problem thanks to an issue found here: [coova-chilli#244](https://github.com/coova/coova-chilli/issues/244).

This was because I checked out the source code straight onto my windows based system via Git and it set the line encodings as `CRLF`. Once I converted all the line endings to `LF` it started working!
